name: test
on: [push]
jobs:
  test-manifests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - app1
        stage:
          - development
          - staging
          - production
        include:
          - stage: development
            aws-access-key-id-secret-name: DEVELOPMENT_AWS_ACCESS_KEY_ID
            aws-secret-access-key-secret-name: DEVELOPMENT_AWS_SECRET_ACCESS_KEY
          - stage: staging
            aws-access-key-id-secret-name: STAGING_AWS_ACCESS_KEY_ID
            aws-secret-access-key-secret-name: STAGING_AWS_SECRET_ACCESS_KEY
          - stage: production
            aws-access-key-id-secret-name: PRODUCTION_AWS_ACCESS_KEY_ID
            aws-secret-access-key-secret-name: PRODUCTION_AWS_SECRET_ACCESS_KEY

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from ${{ matrix.stage }} account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[matrix.aws-access-key-id-secret-name] }}
          aws-secret-access-key: ${{ secrets[matrix.aws-secret-access-key-secret-name] }}
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
      - run: aws eks update-kubeconfig --name terraform-eks-demo
      - name: Install argo
        run: |
          curl -sLO https://github.com/argoproj/argo/releases/download/v2.12.3/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          sudo cp argo-linux-amd64 /usr/local/bin/argo
      - run: argo -n argo-jobs list
